# Setup
title:        Aditya's Website
tagline:      
baseurl:      
paginate:     1

# About/contact
author:
  name:       svaditya
  url:        https://svaditya.github.io

# Gems
gems:
  - jekyll-paginate
  
#Categories
categories: ['Python', 'R']

#Others
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  # do not replace newlines by <br>s
  hard_wrap: false

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: svaditya

encoding: UTF-8

permalink: /blog/:year/:month/:day/:title

