# Setup
title:        Aditya's Website
tagline:      Data Science and Machine Learning Workspace
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       svaditya
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
