# Setup
title:        Aditya's Website
tagline:      
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       svaditya
  url:        https://svaditya.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
